config/routes.rb
Rails.application.routes.draw do
  resources :kittens 
  root "kittens#index"
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [ :show, :edit, :update, :destroy]
  def index 
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens}
    end 
  end

  def show
    respond_to do |format|
      format.html
      format.json {render json: @kittens}
    end 
  end 

  def new 
    @kitten = Kitten.new 
  end 

  def create 
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = "Successfully added kitten!"
      redirect_to @kitten
    else
      flash.now[:alert] = "Failed to add kitten. Check your form."
      render :new
    end
  end
  
  def update
    if @kitten.update(kitten_params)
      flash[:notice] = "Successfully updated kitten!"
      redirect_to @kitten
    else 
      flash.now[:alert] = "Falied to update kitchen. Try again!"
      render :edit
    end
  end 
  def destroy
    @kitten.destroy
    flash[:notice] = "Kitten deleted 🐾"
    redirect_to kittens_path
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |form| %>
  <% if kitten.errors.any? %>
    <div>
      <h2><%= pluralize(kitten.errors.count, "error") %> prevented this kitten from being saved:</h2>
      <ul>
        <% kitten.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness %><br>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render 'form', kitten: @kitten %>
<%= link_to "Back", kittens_path %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>
<%= link_to "Add a new kitten", new_kitten_path %>
<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten_path(kitten) %>
      (<%= link_to "Edit", edit_kitten_path(kitten) %>,
       <%= link_to "Delete", kitten, method: :delete, data: { confirm: "Are you sure?" } %>)
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render 'form', kitten: @kitten %>
<%= link_to "Back", kittens_path %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>
<%= link_to "Edit", edit_kitten_path(@kitten) %> |
<%= link_to "Delete", @kitten, method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to "Back to all kittens", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
  </head>

  <body>
    <p class="notice"><%= flash[:notice] %></p>
    <p class="alert"><%= flash[:alert] %></p>
    <%= yield %>
</body>

</html>